name: Deploy

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: install node 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: install pnpm and dependencies
        run: |
          npm install -g pnpm
          pnpm install

      - name: build
        run: pnpm run build

      - name: copy README.md to dist
        run: cp README.md dist/

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
