# .github/workflows/release.yml

name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'
      - '*-v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Extract and format tag name
        id: format_tag
        shell: bash
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          VERSION=$(echo $TAG_NAME | awk -F- '{print $NF}')
          PROJECT_NAME=$(echo $TAG_NAME | awk -F- '{$NF=""; print $0}' | sed 's/-/ /g' | awk '{for(i=1;i<=NF;i++){$i=toupper(substr($i,1,1)) substr($i,2)}}1')
          FORMATTED_TAG_NAME="$PROJECT_NAME $VERSION"
          echo "FORMATTED_TAG_NAME=$FORMATTED_TAG_NAME" >> $GITHUB_ENV

      - run: npx changelogithub --name "${{ env.FORMATTED_TAG_NAME }}"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
